### PR TITLE
Html text editor with webview

### PR DESCRIPTION
**Pull request by imnapo**
Design new Editor using WebView and Html.

**Pros**
- TextInput jumping issue on Android 
- any html as initial content. no limit for html tags
- large content 
- we will be able to easily add new features like : 
   1. Text align
   1. Float Image beside text
   1. add Links, HR, Tables, Indents and ...

**cons**

- not completely native. dependent to `React-Native-Webview`.
- some current features may not be easy to implement. like `onImageRemoved` prop. But I think we will find a way to implement them later.

### CODE REVIEW

**Comment by imnapo** [comment]
hi @mqtik , @ohpax .
 I'm going to merge this into `next` branch. I also prepared a pre-release version  [2.0.0-rc1](https://github.com/imnapo/react-native-cn-richtext-editor/releases/tag/2.0.0-rc1).
Please check this new pre-release. For more information about how to use this pre-release you may read [README](https://github.com/imnapo/react-native-cn-richtext-editor/blob/next/README.md) and [expo-demo](https://github.com/imnapo/react-native-cn-richtext-editor/blob/next/expo-demo/App.js) project in the `next` branch.
Thanks in advance.

**Comment by mqtik** [comment]
Excellent!
👏 

I'll try it with big data, and all datasets.

**Comment by pacozaa** [comment]
Great job. I will check it out :)

**Comment by mqtik** [comment]
Just tested out..
Awesome.. just awesome.

Clean restart, i'm preparing a few PRs!

So happy...

**Comment by mqtik** [comment]
@imnapo I had problems with the lack of the feature onValueChange (like before).

Tomorrow I'll send a PR fixing this.

**Comment by imnapo** [comment]
You may use `getHtml()` to get html from editor like below:

```
 var result = this.editor.getHtml();
            result.then((resp) => {
                console.log('resp', resp);
            })     
```

**Comment by mqtik** [comment]
I realized,
though I needed the onValueChanged prop so I can update parent components on change (which's exactly what I need).

**Pull request merged**
